env:
  browser: true
  es2021: true

extends:
  - airbnb-base

parserOptions:
  ecmaVersion: 12
  sourceType: module

rules:
  import/extensions: off
  no-param-reassign: off
  no-console: off

overrides: [ { files: ["*.js"] } ]
